# Generated by Django 4.0.6 on 2022-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
